//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilestoneOne
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInOrderTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int ProductId { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual Product ProductTable { get; set; }
    }
}
